const ACTION_TYPES = {
  ACTION_TYPE_MENU_LIST_UPDATE: "MENU_LIST_UPDATE",
  ACTION_TYPE_USER_SIGNUP: "USER_SIGNUP",
  ACTION_TYPE_USER_SIGN_UP_ERROR_UPDATE: "USER_SIGN_UP_ERROR_UPDATE",
};

const actionTypes = { ...ACTION_TYPES };
export default actionTypes;
