export const LATEST_ARTICLES_SUCCESS = 'LATEST_ARTICLES_SUCCESS'
export const LATEST_ARTICLES_FAIL = 'LATEST_ARTICLES_FAIL'
export const LATEST_ARTICLES_REQUEST = 'LATEST_ARTICLES_REQUEST'

export const SELECTED_ARTICLES_SUCCESS = 'SELECTED_ARTICLES_SUCCESS'
export const SELECTED_ARTICLES_FAIL = 'LATEST_ARTICLES_FAIL'
export const SELECTED_ARTICLES_REQUEST = 'LATEST_ARTICLES_REQUEST'

